# Generated by Django 5.2.6 on 2025-09-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Tell Your Name', max_length=250)),
                ('Age', models.IntegerField(help_text='Age should be in range of 18 to 22!')),
                ('DOB', models.DateField(help_text='Enter a Vaild Date.')),
                ('REG_NO', models.IntegerField(help_text='Enter a Vaild Date.')),
            ],
        ),
    ]
